### ISSUE TITLE
M.2 SSD slot

### ISSUE THREAD

**Issue by vicshacks** [andreibleortu/Dell-Vostro-5590-Hackintosh-EFI#2]
does the Vostro 5590 have an extra empty SSD slot? or do i need to replace the (uncompatible) micron 2200s it comes with?

**Comment by andreibleortu** [comment]
Hi!It does have a SATA 2.5in drive bay inside of it. A carrier cage, screws and cable are within the laptop.AndreiOn 30 Jan 2023, at 5:58 PM, vicshacks ***@***.***> wrote:﻿
does the Vostro 5590 have an extra empty SSD slot? or do i need to replace the (uncompatible) micron 2200s it comes with?
